[package]
name = "ykman-rs"
version = "0.1.0"
authors = ["Emil Lundberg <emil@yubico.com>"]
edition = "2018"

[lib]
name = "ykman_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.7.0", features = ["extension-module"] }
